--- #YAML:1.0
name:               Mojolicious-Plugin-HTMLTemplateProRenderer
version:            0.02
abstract:           A Mojoliciuos plugin to render templates using HTML::Template::Pro module
author:
    - Emiliano Bruni (info@ebruni.it)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::Template::Pro:  0.45
    Mojolicious:          4.0
    perl:                 5.006
    Test::Simple:         0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
